substitutions:
  id_prefix: <REPLACE>
  node_name: <REPLACE>
external_components:
  - source:
      type: git
      url: https://github.com/uELKO/esphome_external_components
      ref: patch-1  
sensor:
  - platform: sen6x
    id: sen66
    pm_1_0:
      name: "PM ≤1 µm SEN66"
      id: sen66_pm10
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 9
            send_every: 1
    pm_2_5:
      name: "PM 1-2.5 µm SEN66"
      id: sen66_pm25
      accuracy_decimals: 1
      filters:
        - sliding_window_moving_average:
            window_size: 9
            send_every: 1
    pm_4_0:
      name: "PM 2.5-4 µm SEN66"
      id: sen66_pm40
      accuracy_decimals: 1
    pm_10_0:
      name: "PM 4-10 µm SEN66"
      id: sen66_pm100
      accuracy_decimals: 1
    
    nox:
      name: "NOX SEN66"
      id: sen66_nox
      accuracy_decimals: 1
    co2:
      name: "CO2 SEN66"
      id: sen66_co2
      accuracy_decimals: 0
    temperature:
      name: "Temperature SEN66"
      accuracy_decimals: 1
      id: sen66_temperature_top
    humidity:
      name: "Humidity SEN66"
      accuracy_decimals: 0
      id: sen66_humidity
    voc:
      name: "VOC SEN66"
      id: sen66_voc
      algorithm_tuning:
        index_offset: 100
        learning_time_offset_hours: 12
        learning_time_gain_hours: 12
        gating_max_duration_minutes: 180
        std_initial: 50
        gain_factor: 230
      filters:
        - sliding_window_moving_average:
            window_size: 9
            send_every: 1
    temperature_compensation:
      offset: 0
      normalized_offset_slope: 0
      time_constant: 0
    store_baseline: true
    update_interval: 10s

  - platform: template
    name: "PM ≤10 µm SEN66"
    id: sen66_pm010
    unit_of_measurement: "µg/m³"
    accuracy_decimals: 1
    update_interval: 10s
    lambda: |-
      return id(sen66_pm10).state + id(sen66_pm25).state + id(sen66_pm40).state + id(sen66_pm100).state;
